export const data = {
  categories: ["Furniture", "Lighting", "Accessories"],
  products: [
    {
      id: 1,
      name: "Betty TK1 Chair",
      category: "Furniture",
      description: "Supportive seat webbing design",
      price: 310,
    },
    {
      id: 2,
      name: "Bernard Chair",
      category: "Furniture",
      description: "Solid-wood frame with light cover",
      price: 743,
    },
    {
      id: 3,
      name: "IC Floor Lamp",
      category: "Lighting",
      description: "From Flos explores balance. Light diffused.",
      price: 436,
    },
    {
      id: 4,
      name: "Piccolo Table Lamp",
      category: "Lighting",
      description: "Piccolo is turned on and off when you click the shade",
      price: 34.95,
    },
    {
      id: 5,
      name: "PC Pendant",
      category: "Lighting",
      description: "Pendant constructed in anodised aluminium",
      price: 79500,
    },
    {
      id: 6,
      name: "Countour Place mat",
      category: "Accessories",
      description: "Rectangular place mat in cotton with sewn edges",
      price: 16,
    },
    {
      id: 7,
      name: "Sillon Mirror",
      category: "Accessories",
      description: "Sillon furrowed frame inspired by the Deco movement",
      price: 245,
    },
    {
      id: 8,
      name: "Round Mirror",
      category: "Accessories",
      description: "Gives any room additional depth",
      price: 1013,
    },
  ],
};
