 /**
 ¶  Types
 ¶  @return {string}
 */


export default {
  SET_LOADING_ON: "SET_LOADING_ON",
  LOAD_CATEGORIES: "LOAD_CATEGORIES",
  SET_PRODUCTS:"SET_PRODUCTS",
  SET_CATEGORIES:"SET_CATEGORIES",
  LOAD_DATA: "LOAD_DATA",
  CART_ADD: "CART_ADD",
  CART_UPDATE: "CART_UPDATE",
  CART_DELETE: "CART_DELETE",
  CART_CLEAR: "CART_CLEAR",
  CART_TOTAL_ITEMS: "CART_TOTAL_ITEMS",
  CART_TOTAL_PRICE:" CART_TOTAL_PRICE",
  SET_PAGE: "SET_PAGE",
}